import { PREVIEW_SN_ID } from "../auth/auth"
export function PreviewMode() {
    sessionStorage.setItem('session_id', PREVIEW_SN_ID)
    sessionStorage.setItem('preview_mode', true)

    const currUnix = Math.floor(Date.now() / 1000)
    sessionStorage.setItem('token_expr', currUnix + 3600)

}

export const PREVIEW_SP_PROFILE =
{
    "display_name": "PREVIEW_MODE",
    "id": "1215760807"
}

export const PREVIEW_SN_DATA = 
{
    "data": [
        {
            "description": "Coach Leanne is jetting us on a journey to South Korea for a sugary confection of K-Pop. Don't be fooled by its bouncy and bubbly exterior; this workout packs a mighty punch.",
            "duration": 1052.6036,
            "intensity": 3,
            "isFavorite": true,
            "lastPlayed": "2022-11-12T00:44:31+00:00",
            "launchDate": "2022-11-03T07:00:00+00:00",
            "snSongIdList": [
                1389,
                3277,
                3276,
                3275
            ],
            "spotifyPlaylistId": "2RxGp3qOK6jOB0qdx2ZMj8",
            "title": "Nonstop K-Pop",
            "trackIdList": "Nonstop K-Pop",
            "workoutId": 2518,
            "workoutType": "boxing"
        }
    ]
}
export const PREVIEW_SN_SAVED_TRACKS =
[
    true, true, false, false
] 

export const PREVIEW_SN_TRACKLIST_DATA =
{
    "collaborative": false,
    "description": "&quot;Speeding to Seoul&quot;",
    "external_urls": {
        "spotify": "https://open.spotify.com/playlist/2RxGp3qOK6jOB0qdx2ZMj8"
    },
    "followers": {
        "href": null,
        "total": 3
    },
    "href": "https://api.spotify.com/v1/playlists/2RxGp3qOK6jOB0qdx2ZMj8",
    "id": "2RxGp3qOK6jOB0qdx2ZMj8",
    "images": [
        {
            "height": null,
            "url": "https://i.scdn.co/image/ab67706c0000bebb34f8dc6410c440bd091e6597",
            "width": null
        }
    ],
    "name": " Nonstop K-Pop ",
    "owner": {
        "display_name": "Supernatural",
        "external_urls": {
            "spotify": "https://open.spotify.com/user/dnbz5mv0arwnvakwx57ymuw9b"
        },
        "href": "https://api.spotify.com/v1/users/dnbz5mv0arwnvakwx57ymuw9b",
        "id": "dnbz5mv0arwnvakwx57ymuw9b",
        "type": "user",
        "uri": "spotify:user:dnbz5mv0arwnvakwx57ymuw9b"
    },
    "primary_color": null,
    "public": false,
    "snapshot_id": "MTEsNzJhNjM1Yjg1ZTQzOTRkNjUyOTNhN2MzZGVlNWQwNDFmNjkwM2ExZA==",
    "tracks": {
        "href": "https://api.spotify.com/v1/playlists/2RxGp3qOK6jOB0qdx2ZMj8/tracks?offset=0&limit=100",
        "items": [
            {
                "added_at": "2022-10-24T21:28:29Z",
                "added_by": {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/user/dnbz5mv0arwnvakwx57ymuw9b"
                    },
                    "href": "https://api.spotify.com/v1/users/dnbz5mv0arwnvakwx57ymuw9b",
                    "id": "dnbz5mv0arwnvakwx57ymuw9b",
                    "type": "user",
                    "uri": "spotify:user:dnbz5mv0arwnvakwx57ymuw9b"
                },
                "is_local": false,
                "primary_color": null,
                "track": {
                    "album": {
                        "album_type": "album",
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0"
                                },
                                "href": "https://api.spotify.com/v1/artists/7n2Ycct7Beij7Dj7meI4X0",
                                "id": "7n2Ycct7Beij7Dj7meI4X0",
                                "name": "TWICE",
                                "type": "artist",
                                "uri": "spotify:artist:7n2Ycct7Beij7Dj7meI4X0"
                            }
                        ],
                        "available_markets": [
                            "AD",
                            "AE",
                            "AG",
                            "AL",
                            "AM",
                            "AO",
                            "AR",
                            "AT",
                            "AU",
                            "AZ",
                            "BA",
                            "BB",
                            "BD",
                            "BE",
                            "BF",
                            "BG",
                            "BH",
                            "BI",
                            "BJ",
                            "BN",
                            "BO",
                            "BR",
                            "BS",
                            "BT",
                            "BW",
                            "BY",
                            "BZ",
                            "CA",
                            "CD",
                            "CG",
                            "CH",
                            "CI",
                            "CL",
                            "CM",
                            "CO",
                            "CR",
                            "CV",
                            "CW",
                            "CY",
                            "CZ",
                            "DE",
                            "DJ",
                            "DK",
                            "DM",
                            "DO",
                            "DZ",
                            "EC",
                            "EE",
                            "EG",
                            "ES",
                            "FI",
                            "FJ",
                            "FM",
                            "FR",
                            "GA",
                            "GB",
                            "GD",
                            "GE",
                            "GH",
                            "GM",
                            "GN",
                            "GQ",
                            "GR",
                            "GT",
                            "GW",
                            "GY",
                            "HK",
                            "HN",
                            "HR",
                            "HT",
                            "HU",
                            "ID",
                            "IE",
                            "IL",
                            "IN",
                            "IQ",
                            "IS",
                            "IT",
                            "JM",
                            "JO",
                            "JP",
                            "KE",
                            "KG",
                            "KH",
                            "KI",
                            "KM",
                            "KN",
                            "KW",
                            "KZ",
                            "LA",
                            "LB",
                            "LC",
                            "LI",
                            "LK",
                            "LR",
                            "LS",
                            "LT",
                            "LU",
                            "LV",
                            "LY",
                            "MA",
                            "MC",
                            "MD",
                            "ME",
                            "MG",
                            "MH",
                            "MK",
                            "ML",
                            "MN",
                            "MO",
                            "MR",
                            "MT",
                            "MU",
                            "MV",
                            "MW",
                            "MX",
                            "MY",
                            "MZ",
                            "NA",
                            "NE",
                            "NG",
                            "NI",
                            "NL",
                            "NO",
                            "NP",
                            "NR",
                            "NZ",
                            "OM",
                            "PA",
                            "PE",
                            "PG",
                            "PH",
                            "PK",
                            "PL",
                            "PS",
                            "PT",
                            "PW",
                            "PY",
                            "QA",
                            "RO",
                            "RS",
                            "RW",
                            "SA",
                            "SB",
                            "SC",
                            "SE",
                            "SG",
                            "SI",
                            "SK",
                            "SL",
                            "SM",
                            "SN",
                            "SR",
                            "ST",
                            "SV",
                            "SZ",
                            "TD",
                            "TG",
                            "TH",
                            "TJ",
                            "TL",
                            "TN",
                            "TO",
                            "TR",
                            "TT",
                            "TV",
                            "TW",
                            "TZ",
                            "UA",
                            "UG",
                            "US",
                            "UY",
                            "UZ",
                            "VC",
                            "VE",
                            "VN",
                            "VU",
                            "WS",
                            "XK",
                            "ZA",
                            "ZM",
                            "ZW"
                        ],
                        "external_urls": {
                            "spotify": "https://open.spotify.com/album/3Bi7hl11zYHpw6uE6gAtSs"
                        },
                        "href": "https://api.spotify.com/v1/albums/3Bi7hl11zYHpw6uE6gAtSs",
                        "id": "3Bi7hl11zYHpw6uE6gAtSs",
                        "images": [
                            {
                                "height": 640,
                                "url": "https://i.scdn.co/image/ab67616d0000b2738e0603ae064aec19675faffa",
                                "width": 640
                            },
                            {
                                "height": 300,
                                "url": "https://i.scdn.co/image/ab67616d00001e028e0603ae064aec19675faffa",
                                "width": 300
                            },
                            {
                                "height": 64,
                                "url": "https://i.scdn.co/image/ab67616d000048518e0603ae064aec19675faffa",
                                "width": 64
                            }
                        ],
                        "name": "BDZ",
                        "release_date": "2018-09-12",
                        "release_date_precision": "day",
                        "total_tracks": 10,
                        "type": "album",
                        "uri": "spotify:album:3Bi7hl11zYHpw6uE6gAtSs"
                    },
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0"
                            },
                            "href": "https://api.spotify.com/v1/artists/7n2Ycct7Beij7Dj7meI4X0",
                            "id": "7n2Ycct7Beij7Dj7meI4X0",
                            "name": "TWICE",
                            "type": "artist",
                            "uri": "spotify:artist:7n2Ycct7Beij7Dj7meI4X0"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "disc_number": 1,
                    "duration_ms": 202010,
                    "episode": false,
                    "explicit": false,
                    "external_ids": {
                        "isrc": "JPWP01772493"
                    },
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/1XjipVUiZ6PAAWYbUuSQnS"
                    },
                    "href": "https://api.spotify.com/v1/tracks/1XjipVUiZ6PAAWYbUuSQnS",
                    "id": "1XjipVUiZ6PAAWYbUuSQnS",
                    "is_local": false,
                    "name": "Candy Pop",
                    "popularity": 54,
                    "preview_url": "https://p.scdn.co/mp3-preview/99b9cd8eec21f20e742531da7e38f3857867e362?cid=5d0f7e6ae0c845d3984e00a5fb2d0c0b",
                    "track": true,
                    "track_number": 3,
                    "type": "track",
                    "uri": "spotify:track:1XjipVUiZ6PAAWYbUuSQnS"
                },
                "video_thumbnail": {
                    "url": null
                }
            },
            {
                "added_at": "2022-09-06T22:48:46Z",
                "added_by": {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/user/dnbz5mv0arwnvakwx57ymuw9b"
                    },
                    "href": "https://api.spotify.com/v1/users/dnbz5mv0arwnvakwx57ymuw9b",
                    "id": "dnbz5mv0arwnvakwx57ymuw9b",
                    "type": "user",
                    "uri": "spotify:user:dnbz5mv0arwnvakwx57ymuw9b"
                },
                "is_local": false,
                "primary_color": null,
                "track": {
                    "album": {
                        "album_type": "single",
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/41MozSoPIsD1dJM0CLPjZF"
                                },
                                "href": "https://api.spotify.com/v1/artists/41MozSoPIsD1dJM0CLPjZF",
                                "id": "41MozSoPIsD1dJM0CLPjZF",
                                "name": "BLACKPINK",
                                "type": "artist",
                                "uri": "spotify:artist:41MozSoPIsD1dJM0CLPjZF"
                            }
                        ],
                        "available_markets": [
                            "AD",
                            "AG",
                            "AL",
                            "AO",
                            "AR",
                            "AT",
                            "AU",
                            "BA",
                            "BB",
                            "BE",
                            "BF",
                            "BG",
                            "BI",
                            "BJ",
                            "BO",
                            "BR",
                            "BS",
                            "BW",
                            "BY",
                            "BZ",
                            "CA",
                            "CD",
                            "CG",
                            "CH",
                            "CI",
                            "CL",
                            "CM",
                            "CO",
                            "CR",
                            "CV",
                            "CW",
                            "CZ",
                            "DE",
                            "DJ",
                            "DK",
                            "DM",
                            "DO",
                            "DZ",
                            "EC",
                            "EE",
                            "EG",
                            "ES",
                            "FI",
                            "FR",
                            "GA",
                            "GB",
                            "GD",
                            "GH",
                            "GM",
                            "GN",
                            "GQ",
                            "GR",
                            "GT",
                            "GW",
                            "GY",
                            "HN",
                            "HR",
                            "HT",
                            "HU",
                            "IE",
                            "IS",
                            "IT",
                            "JM",
                            "KE",
                            "KM",
                            "KN",
                            "LC",
                            "LI",
                            "LR",
                            "LS",
                            "LT",
                            "LU",
                            "LV",
                            "LY",
                            "MA",
                            "MC",
                            "MD",
                            "ME",
                            "MG",
                            "MK",
                            "ML",
                            "MR",
                            "MT",
                            "MU",
                            "MW",
                            "MX",
                            "MZ",
                            "NA",
                            "NE",
                            "NG",
                            "NI",
                            "NL",
                            "NO",
                            "NZ",
                            "PA",
                            "PE",
                            "PL",
                            "PT",
                            "PY",
                            "RO",
                            "RS",
                            "RW",
                            "SC",
                            "SE",
                            "SI",
                            "SK",
                            "SL",
                            "SM",
                            "SN",
                            "SR",
                            "ST",
                            "SV",
                            "SZ",
                            "TD",
                            "TG",
                            "TN",
                            "TT",
                            "TZ",
                            "UA",
                            "UG",
                            "US",
                            "UY",
                            "VC",
                            "VE",
                            "XK",
                            "ZA",
                            "ZM",
                            "ZW"
                        ],
                        "external_urls": {
                            "spotify": "https://open.spotify.com/album/0wOiWrujRbxlKEGWRQpKYc"
                        },
                        "href": "https://api.spotify.com/v1/albums/0wOiWrujRbxlKEGWRQpKYc",
                        "id": "0wOiWrujRbxlKEGWRQpKYc",
                        "images": [
                            {
                                "height": 640,
                                "url": "https://i.scdn.co/image/ab67616d0000b273bfd46639322b597331d9ecef",
                                "width": 640
                            },
                            {
                                "height": 300,
                                "url": "https://i.scdn.co/image/ab67616d00001e02bfd46639322b597331d9ecef",
                                "width": 300
                            },
                            {
                                "height": 64,
                                "url": "https://i.scdn.co/image/ab67616d00004851bfd46639322b597331d9ecef",
                                "width": 64
                            }
                        ],
                        "name": "SQUARE UP",
                        "release_date": "2018-06-15",
                        "release_date_precision": "day",
                        "total_tracks": 4,
                        "type": "album",
                        "uri": "spotify:album:0wOiWrujRbxlKEGWRQpKYc"
                    },
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/41MozSoPIsD1dJM0CLPjZF"
                            },
                            "href": "https://api.spotify.com/v1/artists/41MozSoPIsD1dJM0CLPjZF",
                            "id": "41MozSoPIsD1dJM0CLPjZF",
                            "name": "BLACKPINK",
                            "type": "artist",
                            "uri": "spotify:artist:41MozSoPIsD1dJM0CLPjZF"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AG",
                        "AL",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "BA",
                        "BB",
                        "BE",
                        "BF",
                        "BG",
                        "BI",
                        "BJ",
                        "BO",
                        "BR",
                        "BS",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "IE",
                        "IS",
                        "IT",
                        "JM",
                        "KE",
                        "KM",
                        "KN",
                        "LC",
                        "LI",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MK",
                        "ML",
                        "MR",
                        "MT",
                        "MU",
                        "MW",
                        "MX",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "PA",
                        "PE",
                        "PL",
                        "PT",
                        "PY",
                        "RO",
                        "RS",
                        "RW",
                        "SC",
                        "SE",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TN",
                        "TT",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "VC",
                        "VE",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "disc_number": 1,
                    "duration_ms": 239100,
                    "episode": false,
                    "explicit": false,
                    "external_ids": {
                        "isrc": "KRA401800097"
                    },
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/6veFyjNycn6EaNCKhkPXUY"
                    },
                    "href": "https://api.spotify.com/v1/tracks/6veFyjNycn6EaNCKhkPXUY",
                    "id": "6veFyjNycn6EaNCKhkPXUY",
                    "is_local": false,
                    "name": "Forever Young",
                    "popularity": 67,
                    "preview_url": "https://p.scdn.co/mp3-preview/881e3ba2f7d026fc8f59c22d8c8dddd66b577b1d?cid=5d0f7e6ae0c845d3984e00a5fb2d0c0b",
                    "track": true,
                    "track_number": 2,
                    "type": "track",
                    "uri": "spotify:track:6veFyjNycn6EaNCKhkPXUY"
                },
                "video_thumbnail": {
                    "url": null
                }
            },
            {
                "added_at": "2022-09-06T22:48:48Z",
                "added_by": {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/user/dnbz5mv0arwnvakwx57ymuw9b"
                    },
                    "href": "https://api.spotify.com/v1/users/dnbz5mv0arwnvakwx57ymuw9b",
                    "id": "dnbz5mv0arwnvakwx57ymuw9b",
                    "type": "user",
                    "uri": "spotify:user:dnbz5mv0arwnvakwx57ymuw9b"
                },
                "is_local": false,
                "primary_color": null,
                "track": {
                    "album": {
                        "album_type": "album",
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/5BHFSMEjfLVx1JwRWjAOsE"
                                },
                                "href": "https://api.spotify.com/v1/artists/5BHFSMEjfLVx1JwRWjAOsE",
                                "id": "5BHFSMEjfLVx1JwRWjAOsE",
                                "name": "SuperM",
                                "type": "artist",
                                "uri": "spotify:artist:5BHFSMEjfLVx1JwRWjAOsE"
                            }
                        ],
                        "available_markets": [
                            "AD",
                            "AE",
                            "AG",
                            "AL",
                            "AM",
                            "AO",
                            "AR",
                            "AT",
                            "AU",
                            "AZ",
                            "BA",
                            "BB",
                            "BD",
                            "BE",
                            "BF",
                            "BG",
                            "BH",
                            "BI",
                            "BJ",
                            "BN",
                            "BO",
                            "BR",
                            "BS",
                            "BT",
                            "BW",
                            "BY",
                            "BZ",
                            "CA",
                            "CD",
                            "CG",
                            "CH",
                            "CI",
                            "CL",
                            "CM",
                            "CO",
                            "CR",
                            "CV",
                            "CW",
                            "CY",
                            "CZ",
                            "DE",
                            "DJ",
                            "DK",
                            "DM",
                            "DO",
                            "DZ",
                            "EC",
                            "EE",
                            "EG",
                            "ES",
                            "FI",
                            "FJ",
                            "FM",
                            "FR",
                            "GA",
                            "GB",
                            "GD",
                            "GE",
                            "GH",
                            "GM",
                            "GN",
                            "GQ",
                            "GR",
                            "GT",
                            "GW",
                            "GY",
                            "HK",
                            "HN",
                            "HR",
                            "HT",
                            "HU",
                            "ID",
                            "IE",
                            "IL",
                            "IN",
                            "IQ",
                            "IS",
                            "IT",
                            "JM",
                            "JO",
                            "JP",
                            "KE",
                            "KG",
                            "KH",
                            "KI",
                            "KM",
                            "KN",
                            "KR",
                            "KW",
                            "KZ",
                            "LA",
                            "LB",
                            "LC",
                            "LI",
                            "LK",
                            "LR",
                            "LS",
                            "LT",
                            "LU",
                            "LV",
                            "LY",
                            "MA",
                            "MC",
                            "MD",
                            "ME",
                            "MG",
                            "MH",
                            "MK",
                            "ML",
                            "MN",
                            "MO",
                            "MR",
                            "MT",
                            "MU",
                            "MV",
                            "MW",
                            "MX",
                            "MY",
                            "MZ",
                            "NA",
                            "NE",
                            "NG",
                            "NI",
                            "NL",
                            "NO",
                            "NP",
                            "NR",
                            "NZ",
                            "OM",
                            "PA",
                            "PE",
                            "PG",
                            "PH",
                            "PK",
                            "PL",
                            "PS",
                            "PT",
                            "PW",
                            "PY",
                            "QA",
                            "RO",
                            "RS",
                            "RW",
                            "SA",
                            "SB",
                            "SC",
                            "SE",
                            "SG",
                            "SI",
                            "SK",
                            "SL",
                            "SM",
                            "SN",
                            "SR",
                            "ST",
                            "SV",
                            "SZ",
                            "TD",
                            "TG",
                            "TH",
                            "TJ",
                            "TL",
                            "TN",
                            "TO",
                            "TR",
                            "TT",
                            "TV",
                            "TW",
                            "TZ",
                            "UA",
                            "UG",
                            "US",
                            "UY",
                            "UZ",
                            "VC",
                            "VE",
                            "VN",
                            "VU",
                            "WS",
                            "XK",
                            "ZA",
                            "ZM",
                            "ZW"
                        ],
                        "external_urls": {
                            "spotify": "https://open.spotify.com/album/1C1qYeSC9RdgbrKXpZCTSJ"
                        },
                        "href": "https://api.spotify.com/v1/albums/1C1qYeSC9RdgbrKXpZCTSJ",
                        "id": "1C1qYeSC9RdgbrKXpZCTSJ",
                        "images": [
                            {
                                "height": 640,
                                "url": "https://i.scdn.co/image/ab67616d0000b273583c60000e8abc8283853e10",
                                "width": 640
                            },
                            {
                                "height": 300,
                                "url": "https://i.scdn.co/image/ab67616d00001e02583c60000e8abc8283853e10",
                                "width": 300
                            },
                            {
                                "height": 64,
                                "url": "https://i.scdn.co/image/ab67616d00004851583c60000e8abc8283853e10",
                                "width": 64
                            }
                        ],
                        "name": "SuperM - The 1st Mini Album",
                        "release_date": "2019-10-04",
                        "release_date_precision": "day",
                        "total_tracks": 7,
                        "type": "album",
                        "uri": "spotify:album:1C1qYeSC9RdgbrKXpZCTSJ"
                    },
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/5BHFSMEjfLVx1JwRWjAOsE"
                            },
                            "href": "https://api.spotify.com/v1/artists/5BHFSMEjfLVx1JwRWjAOsE",
                            "id": "5BHFSMEjfLVx1JwRWjAOsE",
                            "name": "SuperM",
                            "type": "artist",
                            "uri": "spotify:artist:5BHFSMEjfLVx1JwRWjAOsE"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "disc_number": 1,
                    "duration_ms": 251293,
                    "episode": false,
                    "explicit": false,
                    "external_ids": {
                        "isrc": "KRA301900388"
                    },
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/5WrEilrRI5cIW0DxMvQYPZ"
                    },
                    "href": "https://api.spotify.com/v1/tracks/5WrEilrRI5cIW0DxMvQYPZ",
                    "id": "5WrEilrRI5cIW0DxMvQYPZ",
                    "is_local": false,
                    "name": "Jopping",
                    "popularity": 61,
                    "preview_url": "https://p.scdn.co/mp3-preview/e46b4ad1c66293959fb4c4c8428f91262e60277f?cid=5d0f7e6ae0c845d3984e00a5fb2d0c0b",
                    "track": true,
                    "track_number": 1,
                    "type": "track",
                    "uri": "spotify:track:5WrEilrRI5cIW0DxMvQYPZ"
                },
                "video_thumbnail": {
                    "url": null
                }
            },
            {
                "added_at": "2022-09-06T22:48:49Z",
                "added_by": {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/user/dnbz5mv0arwnvakwx57ymuw9b"
                    },
                    "href": "https://api.spotify.com/v1/users/dnbz5mv0arwnvakwx57ymuw9b",
                    "id": "dnbz5mv0arwnvakwx57ymuw9b",
                    "type": "user",
                    "uri": "spotify:user:dnbz5mv0arwnvakwx57ymuw9b"
                },
                "is_local": false,
                "primary_color": null,
                "track": {
                    "album": {
                        "album_type": "single",
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/1l0mKo96Jh9HVYONcRl3Yp"
                                },
                                "href": "https://api.spotify.com/v1/artists/1l0mKo96Jh9HVYONcRl3Yp",
                                "id": "1l0mKo96Jh9HVYONcRl3Yp",
                                "name": "2NE1",
                                "type": "artist",
                                "uri": "spotify:artist:1l0mKo96Jh9HVYONcRl3Yp"
                            }
                        ],
                        "available_markets": [
                            "AD",
                            "AE",
                            "AG",
                            "AL",
                            "AM",
                            "AO",
                            "AR",
                            "AT",
                            "AU",
                            "AZ",
                            "BA",
                            "BB",
                            "BD",
                            "BE",
                            "BF",
                            "BG",
                            "BH",
                            "BI",
                            "BJ",
                            "BN",
                            "BO",
                            "BR",
                            "BS",
                            "BT",
                            "BW",
                            "BY",
                            "BZ",
                            "CA",
                            "CD",
                            "CG",
                            "CH",
                            "CI",
                            "CL",
                            "CM",
                            "CO",
                            "CR",
                            "CV",
                            "CW",
                            "CY",
                            "CZ",
                            "DE",
                            "DJ",
                            "DK",
                            "DM",
                            "DO",
                            "DZ",
                            "EC",
                            "EE",
                            "EG",
                            "ES",
                            "FI",
                            "FJ",
                            "FM",
                            "FR",
                            "GA",
                            "GB",
                            "GD",
                            "GE",
                            "GH",
                            "GM",
                            "GN",
                            "GQ",
                            "GR",
                            "GT",
                            "GW",
                            "GY",
                            "HK",
                            "HN",
                            "HR",
                            "HT",
                            "HU",
                            "ID",
                            "IE",
                            "IL",
                            "IN",
                            "IQ",
                            "IS",
                            "IT",
                            "JM",
                            "JO",
                            "KE",
                            "KG",
                            "KH",
                            "KI",
                            "KM",
                            "KN",
                            "KW",
                            "KZ",
                            "LA",
                            "LB",
                            "LC",
                            "LI",
                            "LK",
                            "LR",
                            "LS",
                            "LT",
                            "LU",
                            "LV",
                            "LY",
                            "MA",
                            "MC",
                            "MD",
                            "ME",
                            "MG",
                            "MH",
                            "MK",
                            "ML",
                            "MN",
                            "MO",
                            "MR",
                            "MT",
                            "MU",
                            "MV",
                            "MW",
                            "MX",
                            "MY",
                            "MZ",
                            "NA",
                            "NE",
                            "NG",
                            "NI",
                            "NL",
                            "NO",
                            "NP",
                            "NR",
                            "NZ",
                            "OM",
                            "PA",
                            "PE",
                            "PG",
                            "PH",
                            "PK",
                            "PL",
                            "PS",
                            "PT",
                            "PW",
                            "PY",
                            "QA",
                            "RO",
                            "RS",
                            "RW",
                            "SA",
                            "SB",
                            "SC",
                            "SE",
                            "SG",
                            "SI",
                            "SK",
                            "SL",
                            "SM",
                            "SN",
                            "SR",
                            "ST",
                            "SV",
                            "SZ",
                            "TD",
                            "TG",
                            "TH",
                            "TJ",
                            "TL",
                            "TN",
                            "TO",
                            "TR",
                            "TT",
                            "TV",
                            "TW",
                            "TZ",
                            "UA",
                            "UG",
                            "US",
                            "UY",
                            "UZ",
                            "VC",
                            "VE",
                            "VN",
                            "VU",
                            "WS",
                            "XK",
                            "ZA",
                            "ZM",
                            "ZW"
                        ],
                        "external_urls": {
                            "spotify": "https://open.spotify.com/album/7zjLDZzHo2XgvYwpuNwEvK"
                        },
                        "href": "https://api.spotify.com/v1/albums/7zjLDZzHo2XgvYwpuNwEvK",
                        "id": "7zjLDZzHo2XgvYwpuNwEvK",
                        "images": [
                            {
                                "height": 640,
                                "url": "https://i.scdn.co/image/ab67616d0000b2735c041fe9e3c9de436047d86b",
                                "width": 640
                            },
                            {
                                "height": 300,
                                "url": "https://i.scdn.co/image/ab67616d00001e025c041fe9e3c9de436047d86b",
                                "width": 300
                            },
                            {
                                "height": 64,
                                "url": "https://i.scdn.co/image/ab67616d000048515c041fe9e3c9de436047d86b",
                                "width": 64
                            }
                        ],
                        "name": "I Am The Best",
                        "release_date": "2014-12-09",
                        "release_date_precision": "day",
                        "total_tracks": 1,
                        "type": "album",
                        "uri": "spotify:album:7zjLDZzHo2XgvYwpuNwEvK"
                    },
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/1l0mKo96Jh9HVYONcRl3Yp"
                            },
                            "href": "https://api.spotify.com/v1/artists/1l0mKo96Jh9HVYONcRl3Yp",
                            "id": "1l0mKo96Jh9HVYONcRl3Yp",
                            "name": "2NE1",
                            "type": "artist",
                            "uri": "spotify:artist:1l0mKo96Jh9HVYONcRl3Yp"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "disc_number": 1,
                    "duration_ms": 208730,
                    "episode": false,
                    "explicit": false,
                    "external_ids": {
                        "isrc": "USUM71417913"
                    },
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/26EM9sZnQkLLQxixGd88KE"
                    },
                    "href": "https://api.spotify.com/v1/tracks/26EM9sZnQkLLQxixGd88KE",
                    "id": "26EM9sZnQkLLQxixGd88KE",
                    "is_local": false,
                    "name": "I Am The Best",
                    "popularity": 64,
                    "preview_url": "https://p.scdn.co/mp3-preview/a18c0017da0fafaf47d2e4b9441fa250e18be69c?cid=5d0f7e6ae0c845d3984e00a5fb2d0c0b",
                    "track": true,
                    "track_number": 1,
                    "type": "track",
                    "uri": "spotify:track:26EM9sZnQkLLQxixGd88KE"
                },
                "video_thumbnail": {
                    "url": null
                }
            }
        ],
        "limit": 100,
        "next": null,
        "offset": 0,
        "previous": null,
        "total": 4
    },
    "type": "playlist",
    "uri": "spotify:playlist:2RxGp3qOK6jOB0qdx2ZMj8"
}